'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BookDetail
    Public Property BookSerialNo As Integer
    Public Property BookISBN As String
    Public Property BookTitle As String
    Public Property BookAuthor As String
    Public Property BookPublisher As String
    Public Property BookCategory As String

End Class
